// This file is generated by npm run build:icons

export type IconName =
	| 'check'
	| 'chevron-down'
	| 'chevron-up'
	| 'cross-2'
	| 'github-logo'
	| 'linkedin-logo'
	| 'minus'
	| 'plus'
	| 'trash';
